services:
  app:
    build: .
    ports:
      - "3000:3000" #puerto
    volumes:
      - .:/app
    depends_on:
      - db
    command: npm start

  db:
    image: mysql:8.0
    expose:
      - 3307:3307"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "040504EDGAR"
      MYSQL_DATABASE: "todo_list"